default_model: 'gpt-5-mini'
models:
  claude-4.5:
    provider: 'openrouter'
    model: 'anthropic/claude-sonnet-4.5'
    base_url: 'http://localhost:4000'
    api_key: 'none'
    #model: 'google/gemini-2.5-flash-preview'
    #api_key: '******************'
  gpt-5-mini:
    provider: 'openrouter'
    model: 'openai/gpt-5-mini'
    base_url: 'http://localhost:4000'
